### ISSUE TITLE
Utility seems to get stuck while searching for secret.

### ISSUE THREAD

**Issue by shantanuchaudhary24** [microsoft/KeyVaultScannerUtility#1]
**Describe the bug**
I used the utility to search for a secret in one of our key vaults and it seems to get stuck or maybe processing something for a long time. Filing issue here for visibility in case this is happening with others. Not sure if this is related to me using SC-ALT account. Although, that shouldn't be an issue.

**To Reproduce**
1. Login to the utility with SC-ALT account
2. Choose the subscription of key vault on which you want to execute the search for this issue.
3. Select secret and enter the value of secret that exists in key vault.
4. Enter the name of the key vault and click search.

**Expected behavior**
The utility should show the name(s) of the secret where the value is stored.

**Screenshots**
![image](https://user-images.githubusercontent.com/3176457/117620942-a6fcf480-b18e-11eb-9209-5eb8c3d89ce9.png)

**Desktop (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/3176457/117621039-c85de080-b18e-11eb-9b9b-78b64d11c680.png)

 - Powershell
![image](https://user-images.githubusercontent.com/3176457/117621173-efb4ad80-b18e-11eb-9436-ac16b1e46cf8.png)

**Additional context**

**Comment by karansinghkushwah** [comment]
Thanks @shantanuchaudhary24 for reporting the issue, we are looking into it. 

++ @akashkh

**Comment by akashkh** [comment]
@shantanuchaudhary24 , thanks for reporting this issue. We have identified the cause of this and improved our PowerShell code and documentation. To run this tool you need to have 

- Powershell Core or Powershell 7 and above
[Install Powershell core 7.0](https://aka.ms/powershell-release?tag=stable)

- If Az.Keyvault Module is not already Installed, Install by running below command on Powershell core
```
Install-Module -Name Az.keyvault -Force -AllowClobber
```

Please let us know if this resolves your issue.

**Comment by shantanuchaudhary24** [comment]
This will still not be enough. The bat file needs to execute commands using pwsh.exe instead of powershell.exe as on certain systems ps5 and ps7 can co-exist and we will need to provision for that. I have updated readme and bat file on a separate branch but I don't have authorization to create a branch and push changes. I can push my changes to a branch and raise a PR.

```
@echo off

pwsh.exe -noprofile -NoExit -window minimized -command "&{start-process pwsh -ArgumentList '-NoExit -noprofile -window minimized -file "%CD%\KeyVaultscanner.ps1" ' -verb RunAs}"
```

**Comment by akashkh** [comment]
@shantanuchaudhary24 Yes correct and that changes are already there in bat file. Please review

Please download the latest code.

**Comment by karansinghkushwah** [comment]
Please try using new version **KeyVaultScannerUtility- v1.0.2**

**Comment by shantanuchaudhary24** [comment]
Thanks for following up on this guys. The issue is now resolved.
